convert the implementation of the action to TypeScript
dart-lang/setup-dart pull request #75
Opened 2023-02-17 19:36 UTC by devoncarew

Convert the implementation of the action to TypeScript:

- a mostly direct translation from the Bash implementation to TypeScript
- kept the `dart.yml` CI the same, so we could verify correct behavior of the port
- as part of the port, addressed an issue related to auto-detection of the platform architecture (fix https://github.com/dart-lang/setup-dart/issues/59)
- also, added a new action output - `dart-version`
- much of the boilerplate for the action was taken from the https://github.com/actions/typescript-action template repo
- done as part of https://github.com/dart-lang/setup-dart/issues/62
- updated the changelof w/ the relevent changes, and rev'd the action version to 1.5.0-dev
- updated with our std CONTRIBUTING.md file from dart-lang/.github, and added a section on developing the action (building the typescript)

2023-02-17 19:50 UTC, devoncarew commented
@dantup - before I ask for a general review of the implementation and such - do you mind looking over the typescript code here, and the various typescript config files? It's been a while since I've written typescript, and it would be good to have somebody w/ domain expertise look the files over :)

2023-02-18 10:01 UTC, DanTup approved these changes
All looks good to me. I'm not completely familiar with all the latest TS config options/files (my experience is mostly only setting up Dart-Code and keeping it running), but what's there seems reasonable (esp. if the TS action was used as a base).

Added a few questions/nits.

2023-02-19 03:08 UTC, devoncarew reviewed
Thanks for the review! Updated w/ the noted changes.

2023-02-19 03:08 UTC, devoncarew commented on __tests__/main.test.ts
> +  expect(['x64', 'arm64']).toContain(system.getArch())
This was taking advantage that the only likely platforms this test would run on are x64 and macos; but checking `RUNNER_ARCH` sgtm - updated.

2023-02-19 03:08 UTC, devoncarew commented on src/setup.ts
> +    if (error instanceof Error) core.setFailed(error.message)
This was cargo culted from the template, but I agree that catching all errors, but only acting on `Error` instances, doesn't make a lot of sense. I looked at the impl for the go, node, and java setup actions; they all catch all errors here and call `setFailed` w/o any instanceof checking. I updated to match those.

2023-02-19 03:08 UTC, devoncarew commented on src/setup.ts
> +      core.info(url)
Done!

2023-02-19 04:17 UTC, devoncarew commented
@athomas and @mit-mit - adding you both for a general review.

@jonasfj and @isoos - you might want to look at the code around the OIDC token (mostly in the `src/oidc.ts` file).

2023-02-21 07:42 UTC, athomas approved these changes

2023-02-21 07:42 UTC, athomas commented on src/sdk.ts
> +    return null
Should we throw here? Or is there a legit case where there is no `version` file?

The action will end up storing an empty string in the output in this case:
https://github.com/actions/toolkit/blob/0db3029fcfcb1393a2b3ccd14caecd7a3460af4e/packages/core/src/utils.ts#L11

2023-02-21 07:42 UTC, athomas commented on src/setup.ts
> +// TODO: Support version patterns of '2.19.x' to mean the latest 2.19 version.
Maybe instead we should support patterns similar to lower bounds in packages?

2023-02-21 07:42 UTC, athomas commented on src/setup.ts
> +// TODO: Support version patterns of '2.19.x' to mean the latest 2.19 version.
I believe mono_repo has a feature to generate tests using the lower bound of the package, maybe setup-dart could also have that feature?
version = auto -> find pubspec yaml (or perhaps lock) and use the lower bound.

2023-02-21 07:42 UTC, athomas commented on src/versions.ts
> +): Promise<string | null> {
The `null` isn't handled at the call sites, shouldn't we throw instead?

Right now, the action will print "Installing the linux-x64 Dart SDK version null..." and then fail somewhere later (probably when it tries to download from dart-archive, which hopefully doesn't have a file at the URL containing null).

2023-02-21 09:15 UTC, mit-mit requested changes
Would like to chat a bit about this before we go ahead and make the change

2023-03-01 00:46 UTC, devoncarew commented
Converting this PR to a draft in favor of https://github.com/dart-lang/setup-dart/pull/77.

2023-03-04 16:47 UTC, closed without merging